---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: db
    name: database
  namespace: default
 spec:
  clusterIP: 10.100.200.130
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
