---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:        
        - name: db
          image: mariadb:10.4
          volumeMounts:
          - mountPath: "/etc/mysql"
            name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
          - name: MYSQL_DATABASE
            value: "humhub"
          - name: MYSQL_USER
            value: "humhub"
          - name: MYSQL_PASSWORD
            value: "humhub"
          ports:
            - containerPort: 3306
      volumes:      
      - name: mysql
        hostPath:
          path: /var
          type: Directory
