---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: humhub
  labels:
    app: humhub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: humhub
  template:
    metadata:
      labels:
        app: humhub
    spec:
      containers:
        - name: humhub
          image: mriedmann/humhub:stable
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: "/var/www/localhost/htdocs/protected/config"
            name: config
          - mountPath: "/var/www/localhost/htdocs/protected/uploads"
            name: uploads
          - mountPath: "/var/www/localhost/htdocs/protected/modules"
            name: modules
        - name: ambassador-container
          image: stiago/nginx-ambassador
          ports:
            - containerPort: 3000
      volumes:
      - name: config
        hostPath:
          path: /var
          type: Directory
      - name: uploads
        hostPath:
          path: /var
          type: Directory
      - name: modules
        hostPath:
          path: /var
          type: Directory
